---
- hosts: ldbc
  become: false
  tasks:
  - name: Clone datagen branch
    ansible.builtin.git:
      repo: https://github.com/ldbc/ldbc_snb_datagen_spark
      dest: /mnt/ldbc_snb_datagen_spark

  - name: Add an Apt signing key, will not download if present
    ansible.builtin.apt_key:
      keyserver: keyserver.ubuntu.com
      id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    become: true

  - name: Add SBT Repository
    ansible.builtin.apt_repository:
      repo: deb https://repo.scala-sbt.org/scalasbt/debian all main
      filename: sbt
      state: present
    become: true

  - name: Add SBT OLD Repository
    ansible.builtin.apt_repository:
      repo: deb https://repo.scala-sbt.org/scalasbt/debian /
      filename: sbt_old
      state: present
    become: true

  - name: Update repositories cache and install "SBT" package
    ansible.builtin.apt:
      name: sbt
      update_cache: yes
    become: true
