---
- hosts: ldbc
  become: true
  tasks:
  - name: Get AZCopy for Linux
    get_url:
      url: https://azcopyvnext.azureedge.net/release20220721/azcopy_linux_amd64_10.16.0.tar.gz
      dest: /mnt/azcopy_linux_amd64_10.16.0.tar.gz

  - name: Extract AZ Copy
    ansible.builtin.unarchive:
      src: /mnt/azcopy_linux_amd64_10.16.0.tar.gz
      dest: /mnt
      remote_src: yes

  - name: Copy AZ Copy to usr/bin
    ansible.builtin.copy:
      src: /mnt/azcopy_linux_amd64_10.16.0/azcopy
      dest: /usr/bin/azcopy
      mode: '0755'
      remote_src: yes